apiVersion: v1
kind: Service
metadata:
  labels:
    app: random-passwd
  name: random-passwd
  namespace: random-passwd
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 5000
  selector:
    app: random-passwd
  type: NodePort
