name: Random API Pipeline
on: [push]
jobs:
  job1:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DHUB_USER }}
        password: ${{ secrets.DHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: celagus/random-passwd-api:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
